GtkAccelKey and Golang 1.16 issue fix
Please do not merge this PR before Golang 1.16 public version release.

This PR fixes the issue with the GtkAccelKey declaration described below, its purpose is to help users like me who want to test v1.16 using the gotk3 library and to facilitate discussion about this subject to make this solution as better as possible.

_As the current version of Golang 1.16 is still in beta (until February), further changes can be added until its public release._

#### GtkAccelKey and Golang 1.16 issue

altered file: 'accel.go'

Golang 1.16 - Cgo changes [Go 1.16 Release Notes - The Go Programming Language](https://tip.golang.org/doc/go1.16#cgo):
The cgo tool will no longer try to translate C struct bitfields into Go struct fields, even if their size can be represented in Go. The order in which C bitfields appear in memory is implementation dependent, so in some cases the cgo tool produced results that were silently incorrect.

'C' struct definition:

```c
struct GtkAccelKey {
  guint           accel_key;
  GdkModifierType accel_mods;
  guint           accel_flags : 16;
};
```

Cgo compilation errors:

```bash
../../gotk3/gotk3/gtk/accel.go:264:5: val.accel_flags undefined (type _Ctype_struct__GtkAccelKey has no field or method accel_flags)
../../gotk3/gotk3/gtk/accel.go:273:22: obj.accel_flags undefined (type *_Ctype_struct__GtkAccelKey has no field or method accel_flags)
```

Solution:
Need new declaration for GtkAccelKey structure that does not explicitly access to 'accel_flags'.
'accel_flags' value remain accessible using bitwise operations.